version: '3'

services:
  mongodb:
    image: mongo:4.2
    labels:
      svc: "live.mongodb"
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=citizix
      - MONGO_INITDB_ROOT_PASSWORD=S3cret

volumes:
  mongodb: