version: "3"

services:
  mysql:
    image: mysql
    #image: jc21/mariadb-aria:latest #Descomentar esta linea para compilar en rpi con mariaDB
    labels:
      svc: "live.mysql"
    restart: always
    command: >
      --default-authentication-plugin=mysql_native_password
      --max_connections=1000
      --innodb_file_per_table
    environment:
      - MYSQL_ROOT_PASSWORD=Kr@krKr3kr
    volumes:
      - dbdata:/var/lib/mysql
      # - dbdata: /var/lib/mysql
      # - dbdata: /var/lib/mysql
    ports:
      - 3306:3306
      
volumes:
  dbdata:
